global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'nodes'
    static_configs:
      - targets: 
        - 'node1:8080'
        - 'node2:8081'
        - 'node3:8082'
        - 'node4:8083'
        - 'node5:8084'
        - 'node6:8085' 