global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'nodes'
    static_configs:
      - targets:
          - 'node1:8080'
          - 'node2:8081'
          - 'node3:8082'
          - 'node4:8083'
          - 'node5:8084'
          - 'node6:8085'
          - 'node7:8086'
          - 'node8:8087'
          - 'node9:8088'
          - 'node10:8089'
          - 'node11:8090'
          - 'node12:8091'
          - 'node13:8092'
          - 'node14:8093'
          - 'node15:8094'
          - 'node16:8095'
          - 'node17:8096'
          - 'node18:8097'
          - 'node19:8098'
          - 'node20:8099'
          - 'node21:8100'
          - 'node22:8101'
          - 'node23:8102'
          - 'node24:8103'
          - 'node25:8104'
          - 'node26:8105'
          - 'node27:8106'
          - 'node28:8107'
          - 'node29:8108'
          - 'node30:8109'
          - 'node31:8110'
          - 'node32:8111'
          - 'node33:8112'
          - 'node34:8113'
          - 'node35:8114'
          - 'node36:8115'
          - 'node37:8116'
          - 'node38:8117'
          - 'node39:8118'
          - 'node40:8119'
          - 'node41:8120'
          - 'node42:8121'
          - 'node43:8122'
          - 'node44:8123'
          - 'node45:8124'
          - 'node46:8125'
          - 'node47:8126'
          - 'node48:8127'
          - 'node49:8128'
          - 'node50:8129'
          - 'node51:8130'
          - 'node52:8131'
          - 'node53:8132'
          - 'node54:8133'
          - 'node55:8134'
          - 'node56:8135'
          - 'node57:8136'
          - 'node58:8137'
          - 'node59:8138'
          - 'node60:8139'
          - 'node61:8140'
          - 'node62:8141'
          - 'node63:8142'
          - 'node64:8143'
          - 'node65:8144'
          - 'node66:8145'
          - 'node67:8146'
          - 'node68:8147'
          - 'node69:8148'
          - 'node70:8149'
          - 'node71:8150'
          - 'node72:8151'
          - 'node73:8152'
          - 'node74:8153'
          - 'node75:8154'
          - 'node76:8155'
          - 'node77:8156'
          - 'node78:8157'
          - 'node79:8158'
          - 'node80:8159'
          - 'node81:8160'
          - 'node82:8161'
          - 'node83:8162'
          - 'node84:8163'
          - 'node85:8164'
          - 'node86:8165'
          - 'node87:8166'
          - 'node88:8167'
          - 'node89:8168'
          - 'node90:8169'
          - 'node91:8170'
          - 'node92:8171'
          - 'node93:8172'
          - 'node94:8173'
          - 'node95:8174'
          - 'node96:8175'
          - 'node97:8176'
          - 'node98:8177'
          - 'node99:8178'
          - 'node100:8179'
    scrape_interval: 5s
    metrics_path: '/metrics'