{
 "title": "Мониторинг узлов",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Статус узлов",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "node_value_updates", "legendFormat": "Узел {{node_id}}" }
   ]
  },
  {
   "title": "Message Types",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (message_type) (message_count)",
     "legendFormat": "{{message_type}}"
    }
   ]
  },
  {
   "title": "Propagation Time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(message_propagation_time_bucket[1m])) by (le, message_type)",
     "legendFormat": "{{message_type}}"
    }
   ]
  }
 ]
}